FROM python:3.8

WORKDIR /app

COPY ./Share/requirements.txt .
COPY ./Share/wiki-40b.pt .
# コンテナ内で必要なパッケージをインストール
RUN pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt 
RUN pip install python-Levenshtein
# RUN pip install gensim

COPY ./Share/main.py .
EXPOSE 8000
# FastAPIを8000ポートで待機
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]